# Generated by Django 5.2.5 on 2025-09-12 08:01

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                ("slug", models.SlugField(blank=True, max_length=100, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Department",
                "verbose_name_plural": "Departments",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Staff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        help_text="Format: +1234567890",
                        max_length=15,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.",
                                regex="^\\+?1?\\d{9,15}$",
                            )
                        ],
                    ),
                ),
                ("hire_date", models.DateField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                ("position", models.CharField(blank=True, max_length=100)),
                (
                    "bio",
                    models.TextField(
                        blank=True, help_text="A short bio or description"
                    ),
                ),
                (
                    "profile_picture",
                    models.ImageField(
                        blank=True,
                        help_text="Upload a profile picture (optional)",
                        null=True,
                        upload_to="profile_pics/",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="staff_department_members",
                        to="attendance.department",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Attendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sign_in",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the user signed in",
                        null=True,
                        verbose_name="sign in time",
                    ),
                ),
                (
                    "sign_out",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the user signed out",
                        null=True,
                        verbose_name="sign out time",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        auto_now_add=True,
                        help_text="The date of the attendance record",
                        verbose_name="date",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Any additional notes about this attendance record",
                        verbose_name="notes",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When this record was created",
                        null=True,
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="When this record was last updated",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "attendance record",
                "verbose_name_plural": "attendance records",
                "ordering": ["-date", "-sign_in"],
                "indexes": [
                    models.Index(
                        fields=["user", "date"], name="attendance__user_id_c01e0c_idx"
                    ),
                    models.Index(fields=["date"], name="attendance__date_61f2e1_idx"),
                    models.Index(
                        fields=["sign_in"], name="attendance__sign_in_2375ba_idx"
                    ),
                    models.Index(
                        fields=["sign_out"], name="attendance__sign_ou_915b23_idx"
                    ),
                ],
                "unique_together": {("user", "date")},
            },
        ),
        migrations.CreateModel(
            name="LeaveRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        help_text="First day of leave", verbose_name="start date"
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        help_text="Last day of leave", verbose_name="end date"
                    ),
                ),
                (
                    "reason",
                    models.TextField(
                        help_text="Reason for leave", verbose_name="reason"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Approved", "Approved"),
                            ("Rejected", "Rejected"),
                        ],
                        default="Pending",
                        help_text="Current status of the leave request",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When this request was created",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="When this request was last updated",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "review_notes",
                    models.TextField(
                        blank=True,
                        help_text="Notes from the reviewer",
                        verbose_name="review notes",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Admin who reviewed this request",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_leave_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="reviewed by",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leave_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "leave request",
                "verbose_name_plural": "leave requests",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "start_date"],
                        name="attendance__user_id_adc273_idx",
                    ),
                    models.Index(
                        fields=["status"], name="attendance__status_6e3dfd_idx"
                    ),
                    models.Index(
                        fields=["start_date", "end_date"],
                        name="attendance__start_d_5c073b_idx",
                    ),
                ],
            },
        ),
    ]
