# Generated by Django 5.2.5 on 2025-09-25 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="leaverequest",
            name="type",
            field=models.CharField(
                choices=[("Leave", "Leave"), ("Remote Work", "Remote Work")],
                default="Leave",
                help_text="Type of request: Leave or Remote Work",
                max_length=20,
                verbose_name="Request Type",
            ),
        ),
    ]
