# Generated by Django 5.2.5 on 2025-10-10 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0002_leaverequest_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leaverequest",
            name="type",
            field=models.CharField(
                choices=[
                    ("Leave", "Leave"),
                    ("Suggestion", "Suggestion"),
                    ("Remote Work", "Remote Work"),
                ],
                default="Leave",
                help_text="Type of request: Leave or Remote Work",
                max_length=20,
                verbose_name="Request Type",
            ),
        ),
    ]
