# Generated by Django 5.2.5 on 2025-10-17 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0005_alter_leaverequest_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leaverequest",
            name="end_date",
            field=models.DateField(
                blank=True,
                help_text="Last day of leave",
                null=True,
                verbose_name="end date",
            ),
        ),
        migrations.AlterField(
            model_name="leaverequest",
            name="start_date",
            field=models.DateField(
                blank=True,
                help_text="First day of leave",
                null=True,
                verbose_name="start date",
            ),
        ),
        migrations.AlterField(
            model_name="leaverequest",
            name="type",
            field=models.CharField(
                choices=[
                    ("Leave", "Leave"),
                    ("Suggestion_box", "Suggestion_box"),
                    ("Remote Work", "Remote Work"),
                ],
                default="Leave",
                help_text="Type of request: Leave or Remote Work",
                max_length=20,
                verbose_name="Request Type",
            ),
        ),
    ]
