# Generated by Django 5.2.5 on 2025-10-17 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0006_alter_leaverequest_end_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="staff",
            name="barcode",
            field=models.CharField(
                blank=True,
                help_text="Unique barcode/QR code for staff authentication",
                max_length=100,
                unique=True,
            ),
        ),
    ]
