# Generated by Django 5.2.5 on 2025-10-20 16:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0007_staff_barcode"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TodoItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Title of the todo item",
                        max_length=255,
                        verbose_name="title",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Optional description of the todo item",
                        verbose_name="description",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("TODO", "To Do"),
                            ("ONGOING", "Ongoing"),
                            ("DONE", "Done"),
                        ],
                        default="TODO",
                        help_text="Current status of the todo item",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When this todo item was created",
                        verbose_name="created at",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this todo item was moved to ongoing",
                        null=True,
                        verbose_name="started at",
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this todo item was completed",
                        null=True,
                        verbose_name="completed at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="When this todo item was last updated",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who created this todo item",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="todo_items",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "todo item",
                "verbose_name_plural": "todo items",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "status"], name="attendance__user_id_dea0dd_idx"
                    ),
                    models.Index(
                        fields=["status"], name="attendance__status_0ab97b_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="attendance__created_edcd86_idx"
                    ),
                ],
            },
        ),
    ]
