# Generated by Django 5.2.5 on 2025-10-24 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0009_delegatedduty"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance",
            name="location",
            field=models.CharField(
                blank=True,
                help_text="Location from where the user signed in (address or coordinates)",
                max_length=500,
                verbose_name="location",
            ),
        ),
    ]
